export interface InvoiceLine {
    invoiceId: string,
    itemName: string,
    ncmCode: string,
    quantity: number,
    unitaryPrice: number,
    totalPrice: number,
    totalTax: number,
    additionalCosts: number,
    originIcms: string,
    cstIcms: string,
    determinationMode: number,
    valueBaseCalcIcms: number,
    aliquotIcms: number,
    valueIcms: number,
    cstPis: string,
    valueBaseCalcPis: number,
    aliquotPis: number,
    valuePis: number,
    cstCofins: string,
    valueBaseCalcCofins: number,
    aliquotCofins: number,
    valueCofins: number,
    id: string,
}